"""initial requests table

Revision ID: 83a048a6c618
Revises:
Create Date: 2026-08-31 16:22:50.316979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "83a048a6c618"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("upstream_model", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("finish_reason", sa.String(length=32), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("input_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("output_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("pricing_version", sa.String(length=32), nullable=True),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("provider_chain", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cache_status", sa.String(length=16), nullable=False),
        sa.Column("cache_key", sa.String(length=80), nullable=True),
        sa.Column("streamed", sa.Boolean(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("api_key_prefix", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requests")),
    )
    op.create_index(
        op.f("ix_requests_api_key_prefix"), "requests", ["api_key_prefix"], unique=False
    )
    op.create_index(op.f("ix_requests_cache_status"), "requests", ["cache_status"], unique=False)
    op.create_index(op.f("ix_requests_cost_usd"), "requests", ["cost_usd"], unique=False)
    op.create_index(op.f("ix_requests_created_at"), "requests", ["created_at"], unique=False)
    op.create_index(op.f("ix_requests_error_type"), "requests", ["error_type"], unique=False)
    op.create_index(op.f("ix_requests_fallback_used"), "requests", ["fallback_used"], unique=False)
    op.create_index(op.f("ix_requests_model"), "requests", ["model"], unique=False)
    op.create_index(op.f("ix_requests_provider"), "requests", ["provider"], unique=False)
    op.create_index(op.f("ix_requests_request_id"), "requests", ["request_id"], unique=True)
    op.create_index(op.f("ix_requests_status"), "requests", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_requests_status"), table_name="requests")
    op.drop_index(op.f("ix_requests_request_id"), table_name="requests")
    op.drop_index(op.f("ix_requests_provider"), table_name="requests")
    op.drop_index(op.f("ix_requests_model"), table_name="requests")
    op.drop_index(op.f("ix_requests_fallback_used"), table_name="requests")
    op.drop_index(op.f("ix_requests_error_type"), table_name="requests")
    op.drop_index(op.f("ix_requests_created_at"), table_name="requests")
    op.drop_index(op.f("ix_requests_cost_usd"), table_name="requests")
    op.drop_index(op.f("ix_requests_cache_status"), table_name="requests")
    op.drop_index(op.f("ix_requests_api_key_prefix"), table_name="requests")
    op.drop_table("requests")
    # ### end Alembic commands ###
