"""projects, semantic_cache, requests cache+caller cols

Revision ID: 9325628977bc
Revises: 83a048a6c618
Create Date: 2026-08-31 16:55:54.335555

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9325628977bc"
down_revision: Union[str, Sequence[str], None] = "83a048a6c618"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector extension must exist before the semantic_cache table's vector column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("rate_limit_window_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_key_hash"), "projects", ["key_hash"], unique=True)
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "semantic_cache",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_semantic_cache")),
    )
    op.create_index(
        op.f("ix_semantic_cache_created_at"), "semantic_cache", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_semantic_cache_model"), "semantic_cache", ["model"], unique=False)
    op.create_index(
        op.f("ix_semantic_cache_prompt_hash"), "semantic_cache", ["prompt_hash"], unique=False
    )
    op.create_index(
        op.f("ix_semantic_cache_provider"), "semantic_cache", ["provider"], unique=False
    )
    op.add_column(
        "requests", sa.Column("cache_saved_usd", sa.Numeric(precision=12, scale=6), nullable=True)
    )
    op.add_column("requests", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.add_column("requests", sa.Column("project_name", sa.String(length=120), nullable=True))
    op.create_index(op.f("ix_requests_project_id"), "requests", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_requests_project_id_projects"),
        "requests",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_requests_project_id_projects"), "requests", type_="foreignkey")
    op.drop_index(op.f("ix_requests_project_id"), table_name="requests")
    op.drop_column("requests", "project_name")
    op.drop_column("requests", "project_id")
    op.drop_column("requests", "cache_saved_usd")
    op.drop_index(op.f("ix_semantic_cache_provider"), table_name="semantic_cache")
    op.drop_index(op.f("ix_semantic_cache_prompt_hash"), table_name="semantic_cache")
    op.drop_index(op.f("ix_semantic_cache_model"), table_name="semantic_cache")
    op.drop_index(op.f("ix_semantic_cache_created_at"), table_name="semantic_cache")
    op.drop_table("semantic_cache")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_index(op.f("ix_projects_key_hash"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
